### ISSUE TITLE
Creating datasets with non-existing fileIDs should be impossible

### ISSUE THREAD

**Issue by MalinAhlberg** [neicnordic/sensitive-data-archive#1038]
**THIS BUG HAS BEEN FIXED**
Just verify that it works properly and if it is just close the issue

**Describe the bug**
It is possible to create a dataset with incorrect file IDs:
```
sda-admin dataset create --dataset-id dataset1 non-existing-id1 bad-id2
```
This could happen if the user for example mistypes an ID. `sda-admin` reports no error but the services starts to malfunction, and reports this on the following requests:
```
Error: failed to [...], reason: failed to send request, reason: Post "http://localhost:8090/file/accession": EOF
```
**Steps to reproduce**
`sda-admin dataset create --dataset-id dataset1 non-existing-id1 bad-id2`

**A/C**
- [ ] Validate the files before mapping (if the file id exist) in sda-api

**Expected behavior**
- [ ] 

**Additional context**
From #1026.

**Estimation of size**: medium

**Estimation of priority**: medium

**Comment by aaperis** [comment]
VERIFIED:
```
./sda-admin dataset create -user requester@demo.org -dataset-id DATASET001 my-access-100
error: failed to create dataset, reason: server returned status 400: "accession ID not found: my-access-100"
```
