### ISSUE TITLE
Create a list of download API calls that leak the user id

### ISSUE THREAD

**Issue by kostas-kou** [neicnordic/sensitive-data-archive#1095]
As a developer
I want to investigate when the user id is exposed (filepath) when the download APIs are used
so that we know exactly where this is happening and fix it.

A/C:
- Create a list with the findings
  - list of the API calls that give user ids to the user.

**Comment by nanjiangshu** [comment]
List of the API calls that shows the user ids 
# list of endpoints
1. sda-download
    1.1 `GET /metadata/datasets/*dataset/files`
2. admin-api
    2.1 `GET /files`
    2.2 `GET /users/:username/files`
