### ISSUE TITLE
Modify filepath not storing the user id part (to be continued)

### ISSUE THREAD

**Issue by kostas-kou** [neicnordic/sensitive-data-archive#1097]
### Note that changes to the first step makes all other things break, so this has to be kept on a separate branch until it can be merged into the master branch.

As a developer
I want to change the way the filepath is stored in database (remove the user id part)
so that the user is not part of the filepath

### Note

Changes required in these places:
- s3inbox should not store the userid as part of the filename in the database
  - the message to cega should not include the userid in the filepath (no message should include the userid in the filepath).
- ingest needs to be able to find the file, so it has to concatenate the userid
- mapper needs to be able to remove the file from the inbox
- download - no change if it's fixed above
  - s3
  - encrypted s3
  - decrypted REST

**Comment by nanjiangshu** [comment]
API endpoints that reveals the user-ids as listed in the issue neicnordic/sensitive-data-archive#1095 should be fixed

**Comment by MalinAhlberg** [comment]
The filepaths should not start with a `/`
