### ISSUE TITLE
Documentation for running docker compose

### ISSUE THREAD

**Issue by kostas-kou** [neicnordic/sensitive-data-archive#1153]
**Describe the bug**
Lack of documentation about running the stack with docker compose. This is done with the makefile but there is no documentation about that
**Steps to reproduce**

**Expected behavior**
- [ ] To be clear for someone who is not familiar with the sda how it is possible to run the docker compose with all the services

**Additional context**

**Estimation of size**: small

**Comment by nanjiangshu** [comment]
Isn't the documentation already available at https://github.com/neicnordic/sensitive-data-archive/blob/main/GETTINGSTARTED.md? I'm not quite sure which parts we should extend further.

**Comment by jbygdell** [comment]
> Isn't the documentation already available at https://github.com/neicnordic/sensitive-data-archive/blob/main/GETTINGSTARTED.md? I'm not quite sure which parts we should extend further.

If you compare the Makefile with the [Readme](https://github.com/neicnordic/sensitive-data-archive/blob/main/GETTINGSTARTED.md) you will see what parts are missing and needs to be aded/updated.
