### ISSUE TITLE
Be able to run a service with go run

### ISSUE THREAD

**Issue by kostas-kou** [neicnordic/sensitive-data-archive#1155]
**Please describe the feature**
As a developer, I want to be able to run a service be just using go run and a configuration file so that to be faster to check things when I am working on a service.

**Acceptance criteria**
- [ ] Documentation on how to do that (example of how to do for one service)

**Additional context**
Everything else should be run with docker compose as usual except the one service where an ongoing work is happening.

Have a demo for the sprint review

**Estimation of size**: medium

**Comment by MalinAhlberg** [comment]
Would be nice if the documentation contained instructions for how to run download together with the other services
