### ISSUE TITLE
ingest logs fills up memory with error logs

### ISSUE THREAD

**Issue by MalinAhlberg** [neicnordic/sensitive-data-archive#1164]
**Describe the bug**
When running the data_loader in starter-kit-storage-and-interfaces, no key hash is inserted before ingestion starts. That makes ingest loops infinitely, eating all memory while producing logs like this:
```
ingest  | {"level":"info","msg":"Received work (corr-id: 5dd81f8c-9c5c-46a1-ae90-09d13da1dac6, filepath: htsnexus_test_NA12878.bam.c4gh, user: dummy@gdi.eu)","time":"2024-12-06T08:04:56Z"}
ingest  | {"level":"error","msg":"Key hash a7db730b021d942d12ac2a8d02ba77c8c91fe4ca61681f9e1450536c546ae72a could not be set for fileID 5dd81f8c-9c5c-46a1-ae90-09d13da1dac6: (pq: insert or update on table \"files\" violates foreign key constraint \"files_key_hash_fkey\")","time":"2024-12-06T08:04:57Z"}
```

**Steps to reproduce**
Run `docker compose -f docker-compose-demo.yml up -d` in `starter-kit-storage-and-interfaces`, or run the steps manually without the starter kit.

**Expected behavior**
- [ ] One error is reported
- [ ] Logs are not exploding

**Additional context**
See also #1037 and #1027

**Estimation of size**: medium

**Estimation of priority**: high

**Comment by jbygdell** [comment]
So the reason for this is that ingest will just `Nack` any DB related error to cope with connection problems with the DB.

The `fix` for this issue will be to add a Startup check that ensures that the DB has a `keyHash` registered before it can start reading messages from the MQ.
