### ISSUE TITLE
[s3inbox] Resume multipart uploads

### ISSUE THREAD

**Issue by aaperis** [neicnordic/sensitive-data-archive#255]
Currently interrupted multipart uploads cannot be resumed.

DoD: Resume an interrupted upload to a ceph s3 backend using `s3cmd`.

**Comment by MalinAhlberg** [comment]
Links:
https://github.com/neicnordic/sensitive-data-archive/blob/main/.github/integration/sda-integration.yml
https://github.com/neicnordic/sda-s3proxy

**Comment by aaperis** [comment]
https://github.com/NBISweden/sda-tools/tree/main/ceph-dev-cluster
