### ISSUE TITLE
[sda-auth] Download configuration file fails the first time

### ISSUE THREAD

**Issue by dbampalikis** [neicnordic/sensitive-data-archive#431]
The button for downloading the configuration file fails the first time the user tries to click it. Going through the login process again, solves the problem, however, it's not optimal.

**Comment by viklund** [comment]
Is this still the case?

**Comment by viklund** [comment]
Apparently Yes.

**Comment by jbygdell** [comment]
Found what might be a solution to this, testable [here](https://login.test.bp.nbis.se/)
