### ISSUE TITLE
[sda-download] Connect re-encryption service

### ISSUE THREAD

**Issue by dbampalikis** [neicnordic/sensitive-data-archive#698]
As an sda-dev
I want to be able to re-encrypt headers through sda-download
In order to be able to export files encrypted with the user's public key

The re-encryption service exists in the [sensitive-data-archive repo](https://github.com/neicnordic/sensitive-data-archive/tree/main/sda/cmd/reencrypt), but is currently not connected to sda-download

A/C
- Be able to send a public key and a header and get back a new header encrypted with this public key
- Add integration tests (see e.g. docker compose file posted below)

**Comment by blankdots** [comment]
this should have been done as part of https://github.com/neicnordic/sda-download/pull/330

**Comment by dbampalikis** [comment]
> this should have been done as part of [neicnordic/sda-download#330](https://github.com/neicnordic/sda-download/pull/330)

I agree and I thought that this was the case to be honest. However, the re-encryption service was merged in #668 and that doesn't work with sda-download

**Comment by pontus** [comment]
I don't think the reencrypt service has been brought in to charts yet, and it needs to be added as a service in the compose file for download to support test/development.

**Comment by jbygdell** [comment]
> I don't think the reencrypt service has been brought in to charts yet, and it needs to be added as a service in the compose file for download to support test/development.

The re-encrypt service exists in the sda compose file: https://github.com/neicnordic/sensitive-data-archive/blob/abbd2971f8b480b4dd09d6b0079e350dbc51a5b1/.github/integration/sda-s3-integration.yml#L306-L318

It is not part of the chart yet since it is not fully functional i.e. other services exists that can talk to it.
