### ISSUE TITLE
[sda-download] Add user-agent header

### ISSUE THREAD

**Issue by dbampalikis** [neicnordic/sensitive-data-archive#701]
As a developer
I want sda-download to read the User-Agent header
In order to decide which key header should be used for re-encryption

Description
The htsget is currently forwarding all the header from any user request, including the ones containing the public keys of the user and the htsget server. We have defined two different header, namely `client-public-key` and `server-public-key`. Since these headers are passed in every request, we need a way to figure out if the request comes from the user or the htsget server, and re-encrypt accordingly. The idea is to use a `user-agent` header, with a specific value for the htsget server

**Comment by viklund** [comment]
I think htsget-rs is the client of download and should therefore just replace the `client-public-key` with it's own key when making the request to the `sda-download` server. In case htsget need to do some more shenanigans to the client of htsget they should still have access to that key while processing the request.
