### ISSUE TITLE
Create architecture diagram for how CEGA cancel messages are handled

### ISSUE THREAD

**Issue by aaperis** [neicnordic/sensitive-data-archive#821]
As an sda-admin,
I want to have a diagram for the cancel messages workflow
so that I can discuss it with colleagues and converge it to a solution that can will eventually be implemented.

Background:
- see docs from CEGA about `cancel` messages

A/C:
- an architecture diagram in miro for how this is currently handled
- an arranged meeting to discuss the diagram and the cancel flow

**Comment by jbygdell** [comment]
```
Routing key: cancel

Description
Message sent when a run or analysis is deleted, or edited to change the linked file in the Submitter Portal. The purpose of this message is to clean up the staging area, in case the file is still there.
```

**Comment by kostas-kou** [comment]
Diagram can be found [here](https://miro.com/app/board/uXjVNA7yMQU=/#tpicker-content)

**Comment by nanjiangshu** [comment]
Great work @kostas-kou! I have a few questions though.
1. If I understand corrected, the cancel message is original sent by the user from the submission portal, e.g. centralEGA, should this component also be added to the diagram
2. According to https://github.com/neicnordic/sensitive-data-archive/pull/384, it seems also the services `verify` and `finalize` will react on the cancel message. Should they also be included in the component?

**Comment by kostas-kou** [comment]
About your second comment @nanjiangshu the message with type=cancel comes only in the ingest message and the only thing that verify and analyze do is to check in the database if the file has status disabled and then they do nothing, so there is not much happening there

**Comment by kostas-kou** [comment]
I added your first comment as well
