### ISSUE TITLE
Grant select permission on `dataset_event_log` to "Download"

### ISSUE THREAD

**Issue by Parisa68** [neicnordic/sensitive-data-archive#866]
**Please describe the feature**
As a developer, I want the role "Download" in database to have permission to select on dataset_event_log table in order to be able to get the latest event of a dataset, ensuring users do not download datasets that are not "released".

**Acceptance criteria**
- [ ] The "Download" role is granted select permission on the dataset_event_log table.
- [ ] A sutaible migration script is provided for this change.

**Additional context**
It leads to a new version of postgresql.

**Estimation of size**: small

**Estimation of priority**: high

**Comment by viklund** [comment]
Is this for the Java implementation of data out or is it the go `sda-download`?

**Comment by kjellp** [comment]
It would be for both if the the roles are being used by both I guess. We were working from sda-doa side when we discovered it. 

If a data out service is connecting with the privileged "master postgres user", the roles are (possibly) ignored all together. We are still using the lega_in and lega_out users that get their privileges through how they are mapped to roles in the DB schema.
