### ISSUE TITLE
Fix broken actions

### ISSUE THREAD

**Issue by pontus** [neicnordic/sensitive-data-archive#903]
Supposedly since @blankdots departed, some automatic workflows fail, e.g. https://github.com/neicnordic/sensitive-data-archive/actions/runs/9466006811, we should fix those.

It's also possible things can be done without relying on a personal access token (and thus a specific member), if so, that's better. Check out https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs and see if it can help.

**Comment by blankdots** [comment]
you need someone with admin privileges of the org, and i think you need to change it in neic-sda as well

**Comment by aaperis** [comment]
Is this still relevant?

**Comment by viklund** [comment]
We belevie this is not an issue anymore.
